name: weather_forecast_app
description: A weather forecast app for HNG Internship Stage 3.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  page_transition: ^2.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # No custom assets needed